# Generated by Django 5.2.4 on 2025-08-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del trabajo')),
                ('description', models.TextField(verbose_name='Descripción del trabajo realizado')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagen del trabajo')),
                ('service_type', models.CharField(max_length=100, verbose_name='Tipo de servicio')),
                ('completed_date', models.DateField(verbose_name='Fecha de finalización')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Trabajo destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Trabajo en galería',
                'verbose_name_plural': 'Trabajos en galería',
                'ordering': ['-completed_date'],
            },
        ),
    ]
