# Generated by Django 5.2.4 on 2025-08-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='service_code',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Código de servicio'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='Mensaje del admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del mensaje')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contact.contact', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Mensaje de servicio',
                'verbose_name_plural': 'Mensajes de servicio',
                'ordering': ['created_at'],
            },
        ),
    ]
