# Generated by Django 5.2.4 on 2025-08-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_service_code_servicemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemessage',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contact.contact', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='servicemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='servicemessage',
            name='is_from_admin',
            field=models.BooleanField(default=False, verbose_name='Es del administrador'),
        ),
        migrations.CreateModel(
            name='ServiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_notes', to='contact.contact', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Nota de servicio',
                'verbose_name_plural': 'Notas de servicio',
                'ordering': ['-created_at'],
            },
        ),
    ]
