# Generated by Django 5.2.4 on 2025-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_servicemessage_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenote',
            name='manual_date',
            field=models.DateTimeField(blank=True, help_text='Fecha que se mostrará al usuario (dejar vacío para usar fecha automática)', null=True, verbose_name='Fecha manual'),
        ),
    ]
