# Generated by Django 5.2.4 on 2025-08-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_servicenote_manual_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR'),
        ),
    ]
