# Generated by Django 5.2.4 on 2025-08-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service_code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código de servicio'),
        ),
    ]
